@url_base=http://localhost:3333
@path=categories

###
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "name": "SUV",
  "description": "categoria utilitário"
}

###
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "name": "Sedan",
  "description": "categoria carro de passeio"
}
